export const AUTH_ROUTES = {
  auth: "/auth/*",
  chefSignUp: "chef-signup",
  linkChefSignUp: "/auth/chef-signup",
  chefLogin: "chef-login",
  linkChefLogin: "/auth/chef-login",
  chefForgotPassword: "chef-forgot-password",
  linkChefForgotPassword: "/auth/chef-forgot-password",
  chefResetPassword: "chef-reset-password",
  linkChefResetPassword: "/auth/chef-reset-password",

  customerSignUp: "customer-signup",
  linkCustomerSignUp: "/auth/customer-signup/",
  customerLogin: "customer-login/:navigateFrom?/:navigateFrom2?",
  linkCustomerLogin: "/auth/customer-login",
  linkCustomerFromLogin: "/auth/customer-login/:navigateFrom?",
  linkCustomerExploreCheckoutLogin: "/auth/customer-login/explore",
  linkCustomerShopCheckoutLogin: "/auth/customer-login/explore/:businessName",
  customerForgotPassword: "customer-forgot-password",
  linkCustomerForgotPassword: "/auth/customer-forgot-password",
  customerResetPassword: "customer-reset-password",
  linkCustomerResetPassword: "/auth/customer-reset-password",

  companySignUp: "company-signup",
  linkCompanySignUp: "/auth/company-signup",
  companyLogin: "company-login/:navigateFrom?",
  linkCompanyLogin: "/auth/company-login",
  linkCompanyCheckoutLogin: "/auth/company-login/explore",
  companyForgotPassword: "company-forgot-password",
  linkCompanyForgotPassword: "/auth/company-forgot-password",
  companyResetPassword: "company-reset-password",
  linkCompanyResetPassword: "/auth/company-reset-password",

  adminLogin: "admin-login",
  linkAdminLogin: "/auth/admin-login",
};

export const DROPP_ROUTES = {};

export const HOME_ROUTES = {
  explore: "explore",
  linkExplore: "/explore",
  exploreChef: "explore/:businessName/:foodName?",
  linkExploreChef: "/explore/:businessName/:foodName?",
  exploreStorefront: "storefront-shop/:businessName",
  linkExploreStorefront: "/storefront-shop/:businessName",
  exploreQsr: "restaurant/qsr/:businessName",
  linkExploreQsr: "/restaurant/qsr/:businessName",
  exploreRestaurant: "restaurant/:businessName/:table",
  linkExploreRestaurant: "/restaurant/:businessName/:table",
  exploreRestaurantEdit: "restaurant/:businessName/:table/add/:menuId",
  linkExploreRestaurantEdit: "/restaurant/:businessName/:table/add/:menuId",
  previewStorefront: "preview/storefront/:businessName",
  linkPreviewStorefront: "/preview/storefront/:businessName",
  previewRestaurant: "preview/restaurant/:businessName",
  linkPreviewRestaurant: "/preview/restaurant/:businessName",
  previewChef: "preview/:businessName",
  linkPreviewChef: "/preview/:businessName",
  chefLandingPage: "home-chef",
  linkChefLandingPage: "/home-chef",
  privacyPolicy: "privacy-policy",
  linkPrivacyPolicy: "/privacy-policy",
  foodSafety: "food-safety",
  linkFoodSafety: "/food-safety",
  termsService: "terms-service",
  linkTermsService: "/terms-service",
  events: "events/:eventName",
  linkEvents: "/events/:eventName",
  eventRegister: "events/register/:eventName",
  linkEventRegister: "/events/register/:eventName",
  subscription: "subscription",
  linkSubscription: "/subscription",
  companies: "companies",
  linkCompanies: "/companies",
};

export const CUSTOMER_ROUTES = {
  customer: "customer/*",
  customerDashboard: "customer/dashboard",
  linkCustomer: "/customer",

  customerWallet: "wallet",
  linkCustomerWallet: "/customer/wallet",
  customerOrders: "orders",
  linkCustomerOrders: "/customer/orders",
  customerFavourites: "favourites",
  linkCustomerFavourites: "/customer/favourites",
  customerChat: "chat",
  linkCustomerChat: "/customer/chat",
  customerSettings: "settings",
  linkCustomerSettings: "/customer/settings",
  customerSubscription: "subscription",
  linkCustomerSubscription: "/customer/subscription",
};

export const CHEF_ROUTES = {
  chef: "/chef/*",
  linkChef: "/chef",
  chefOrders: "orders",
  linkChefOrders: "/chef/orders",
  chefDineIn: "dine-in",
  linkChefDineIn: "/chef/dine-in",
  chefTableManagement: "dine-in/tables",
  linkChefTableManagement: "/chef/dine-in/tables",
  chefSectionManagement: "dine-in/section",
  linkChefSectionManagement: "/chef/dine-in/section",
  kitchen: "kitchen",
  linkKitchen: "/chef/kitchen",
  kitchenMenu: "kitchen-menu",
  linkKitchenMenu: "/chef/kitchen-menu",
  restaurantDineIn: "restaurant/dine-in",
  linkRestaurantDineIn: "/chef/restaurant/dine-in",
  chefMenu: "menu",
  linkChefMenu: "/chef/menu",
  chefMenuOnline: "menu/online",
  linkChefMenuOnline: "/chef/menu/online",
  chefMenuDineIn: "menu/dine-in",
  linkChefMenuDineIn: "/chef/menu/dine-in",
  chefWallet: "wallet",
  linkChefWallet: "/chef/wallet",
  chefChat: "chat",
  linkChefChat: "/chef/chat",
  chefSettings: "settings",
  linkChefSettings: "/chef/settings",
  chefLandingPage: "chef-explore",
  linkChefLandingPage: "/chef-explore",
  subChefs: "sub-chef",
  linkSubChefs: "/chef/sub-chef",
  chefReports: "reports",
  linkChefReports: "/chef/reports",
  chefInventory: "inventory",
  linkChefInventory: "/chef/inventory",
  chefTeams: "teams",
  linkChefTeams: "/chef/teams",
  chefStocktake: "inventory/stocktake",
  linkChefStocktake: "/chef/inventory/stocktake",
};

export const STOREFRONT_ROUTES = {
  storefront: "/storefront/*",
  linkStorefront: "/storefront",
  storefrontOrders: "orders",
  linkStorefrontOrders: "/storefront/orders",
  storefrontMenu: "menu",
  linkStorefrontMenu: "/storefront/menu",
  storefrontWallet: "wallet",
  linkStorefrontWallet: "/storefront/wallet",
  storefrontChat: "chat",
  linkStorefrontChat: "/storefront/chat",
  storefrontSettings: "settings",
  linkStorefrontSettings: "/storefront/settings",
  storefrontLandingPage: "storefront-explore",
  linkStorefrontLandingPage: "/storefront-explore",
  storefrontReports: "reports",
  linkStorefrontReports: "/storefront/reports",
};

export const QSR_ROUTES = {
  qsr: "/qsr/*",
  linkQsr: "/qsr",
  qsrOrders: "orders",
  linkQsrOrders: "/qsr/orders",
  qsrMenu: "menu",
  linkQsrMenu: "/qsr/menu",
  qsrCashier: "cashier-management",
  linkQsrCashier: "/qsr/cashier-management",
  qsrAudit: "audit",
  linkQsrAudit: "/qsr/audit",
  qsrSettings: "settings",
  linkQsrSettings: "/qsr/settings",
  qsrReports: "reports",
  linkQsrReports: "/qsr/reports",
};

export const SUB_CHEF_ROUTES = {
  subChef: "/sub-chef/*",
  linkSubChef: "/sub-chef",
  subChefReports: "reports",
  linkSubChefReports: "/sub-chef/reports",
  subChefDineIn: "dine-in",
  linkSubChefDineIn: "/sub-chef/dine-in",
  subChefTableManagement: "tables",
  linkSubChefTableManagement: "/sub-chef/tables",
  subChefMenu: "menu",
  linkSubChefMenu: "/sub-chef/menu",
  subChefMenuOnline: "menu/online",
  linkSubChefMenuOnline: "/sub-chef/menu/online",
  subChefMenuDineIn: "menu/dine-in",
  linkSubChefMenuDineIn: "/sub-chef/menu/dine-in",
  kitchen: "kitchen",
  linkKitchen: "/sub-chef/kitchen",
  kitchenMenu: "kitchen-menu",
  linkKitchenMenu: "/sub-chef/kitchen-menu",
  subChefSettings: "settings",
  linkSubChefSettings: "/sub-chef/settings",
};

export const WAITER_ROUTES = {
  waiter: "/waiter/*",
  linkWaiter: "/waiter",
};

export const QSR_SUBADMIN_ROUTES = {
  qsrSubAdmin: "/qsr-sub-admin/*",
  linkQsrSubAdmin: "/qsr-sub-admin",
  qsrSubAdminMenu: "menu",
  linkQsrSubAdminMenu: "/qsr-sub-admin/menu",
  qsrSubAdminCashier: "cashier-management",
  linkQsrSubAdminCashier: "/qsr-sub-admin/cashier-management",
  qsrSubAdminSettings: "settings",
  linkQsrSubAdminSettings: "/qsr-sub-admin/settings",
  // qsrSubAdminReports: "reports",
  // linkQsrSubAdminReports: "/qsr-sub-admin/reports",
};

export const CASHIER_ROUTES = {
  cashier: "/cashier/*",
  linkCashier: "/cashier",
  cashierLogin: "/cashier/*",
  linkCashierLogin: "/cashier",
  cashierOrders: "orders",
  linkCashierOrders: "/cashier/orders",
  cashierMenu: "menu",
  linkCashierMenu: "/cashier/menu",
};

export const ADMIN_ROUTES = {
  admin: "/admin/*",
  linkAdmin: "/admin",
  adminSettings: "settings",
  linkAdminSettings: "/admin/settings",
};

export const COMPANY_ROUTES = {
  company: "/company/*",
  linkCompany: "/company",
  companyEmployees: "employees",
  linkCompanyEmployees: "/company/employees",
  companyWallet: "wallet",
  linkCompanyWallet: "/company/wallet",
  companySettings: "settings",
  linkCompanySettings: "/company/settings",
  // companyLandingPage: "company-home",
  // linkCompanyLandingPage: "/company-home",
};
